### ISSUE TITLE
stuck in thread with sidekiq

### ISSUE THREAD

**Issue by rayway30419** [alloy/lowdown#15] opened 2016-04-15 09:17 UTC
HI, 
I use sidekiq to send the push notification and found that the delivery job does not terminate itself after the job had been done.

I send TTIN signal to sidekiq process and get many warning of celluloid at stack.

Can you give me some suggestions to solve this problem, does it cause by sidekiq or celluloid? 

```
2016-04-15T09:11:07.903Z 32518 TID-8z7ms WARN: Thread TID-owhjjp2w0 
2016-04-15T09:11:07.903Z 32518 TID-8z7ms WARN: /home/deployer/ruby_servers/pushnotificationmanager/shared/bundle/ruby/2.2.0/gems/celluloid-io-0.17.3/lib/celluloid/io/reactor.rb:58:in `select'
/home/deployer/ruby_servers/pushnotificationmanager/shared/bundle/ruby/2.2.0/gems/celluloid-io-0.17.3/lib/celluloid/io/reactor.rb:58:in `run_once'
/home/deployer/ruby_servers/pushnotificationmanager/shared/bundle/ruby/2.2.0/gems/celluloid-0.17.3/lib/celluloid/mailbox/evented.rb:50:in `check'
/home/deployer/ruby_servers/pushnotificationmanager/shared/bundle/ruby/2.2.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:155:in `block in run'
/home/deployer/ruby_servers/pushnotificationmanager/shared/bundle/ruby/2.2.0/gems/timers-4.1.1/lib/timers/group.rb:66:in `wait'
/home/deployer/ruby_servers/pushnotificationmanager/shared/bundle/ruby/2.2.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:152:in `run'
/home/deployer/ruby_servers/pushnotificationmanager/shared/bundle/ruby/2.2.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:131:in `block in start'
/home/deployer/ruby_servers/pushnotificationmanager/shared/bundle/ruby/2.2.0/gems/celluloid-essentials-0.20.5/lib/celluloid/internals/thread_handle.rb:14:in `block in initialize'
/home/deployer/ruby_servers/pushnotificationmanager/shared/bundle/ruby/2.2.0/gems/celluloid-0.17.3/lib/celluloid/actor/system.rb:78:in `block in get_thread'
/home/deployer/ruby_servers/pushnotificationmanager/shared/bundle/ruby/2.2.0/gems/celluloid-0.17.3/lib/celluloid/group/spawner.rb:50:in `call'
/home/deployer/ruby_servers/pushnotificationmanager/shared/bundle/ruby/2.2.0/gems/celluloid-0.17.3/lib/celluloid/group/spawner.rb:50:in `block in instantiate'
```

```
class ApplePushNotificationService
  def initialize(cert_dev, cert_pro)
    @cert_dev = cert_dev
    @cert_pro = cert_pro
    @pro_mutex = Mutex.new
    @dev_mutex = Mutex.new
  end

  def deliver(tokens, payload, is_dev = false)
    begin
      failure_tokens = []
      client = production if is_dev == false
      client = development if is_dev == true
      client.connect do |group|
        tokens.each do |token|
          notification = notification(token, payload)
          group.send_notification(notification) do |response|
            if !response.success? 
              failure_tokens.push token if is_dev == false
            end
          end
        end  
      end     
      deliver(failure_tokens, payload, true) if is_dev == false && failure_tokens.present?
    rescue Exception => e
      Rails.logger.error "[!] Exception occurred at: #{e.inspect}\n\t#{e.backtrace.join("\n\t")}"
    end
  end

private

  def production
    client = nil
    @pro_mutex.synchronize do
      require 'lowdown'
      @pro_client ||= Lowdown::Client.production(true, certificate: @cert_pro)
      client = @pro_client
    end
    client
  end

  def development
    client = nil
    @dev_mutex.synchronize do
      require 'lowdown'
      @dev_client ||= Lowdown::Client.production(false, certificate: @cert_dev)
      client = @dev_client
    end
    client
  end

  def notification(token, payload, expires_in = Time.now + 7.days)
    require 'lowdown'
    notification = Lowdown::Notification.new(token: token, expiration: expires_in)
    notification.payload = payload
    notification
  end
end

```

**Comment by alloy** [comment] 2016-04-15 09:34
Can you maybe increase your log level to see if the connection closes when you expect it to? E.g. `Celluloid.logger.level = Logger::DEBUG`.

As a side-note, I also wonder about the use of `users` in your delivery method. Where do they come from? Are they safe to pass across threads? Re https://github.com/alloy/lowdown#threading

**Comment by rayway30419** [comment] 2016-04-15 10:39
Sorry, I simplify this code, 'users' should be 'tokens'. 
'users' is a array of hash with token and language to format localism notification.

I am not sure where shoud I set the logger level on Celluloid.

**Comment by alloy** [comment] 2016-04-15 10:41
> Sorry, I simplify this code, 'users' should be 'tokens'. 
> 'users' is a array of hash with token and language to format localism notification.

Cool, that should be fine then 👍 

> I am not sure where shoud I set the logger level on Celluloid.

I would do it just after the `require 'lowdown'` line.

**Comment by rayway30419** [comment] 2016-04-15 11:03
I set Celluloid.logger here, and have no idea what should I do.
```
def production
    client = nil
    @pro_mutex.synchronize do
      require 'lowdown'
      Celluloid.logger.level = Logger::DEBUG
      Celluloid.logger = ::Logger.new("celluloid.log")
      @pro_client ||= Lowdown::Client.production(true, certificate: @cert_pro, keep_alive: true)
      client = @pro_client
    end
    client
  end
```

**Comment by alloy** [comment] 2016-04-15 11:06
You should reverse those two statements, for the logger instance to actually get the debug level. Afterwards the process should create a `celluloid.log` file in the current working dir of your app’s process.

However, in retrospect, I’m thinking that raising the level to debug isn’t even necessary, as the connection closing will be logged at the info level: https://github.com/alloy/lowdown/blob/master/lib/lowdown/connection.rb#L121.

And instead of assigning a new file to the logger, you can also do this to have the logs show up in your existing Rails logs: `Celluloid.logger = Rails.logger`

**Comment by rayway30419** [comment] 2016-04-15 11:16
Clients looks like closed well
```
I, [2016-04-15T11:11:43.525191 #22319]  INFO -- : [APNS Connection#0x4fdbe08] Connecting...
I, [2016-04-15T11:11:43.527319 #22319]  INFO -- : [APNS Connection#0x4fc4050] Connecting...
I, [2016-04-15T11:11:43.528741 #22319]  INFO -- : [APNS Connection#0x50576c0] Connecting...
I, [2016-04-15T11:11:43.529335 #22319]  INFO -- : [APNS Connection#0x503cfa0] Connecting...
W, [2016-04-15T11:11:43.538098 #22319]  WARN -- : [APNS Connection#0x50576c0] Defer performing request, because the connection has not been established yet.
W, [2016-04-15T11:11:43.539381 #22319]  WARN -- : [APNS Connection#0x503cfa0] Defer performing request, because the connection has not been established yet.
I, [2016-04-15T11:11:43.650337 #22319]  INFO -- : [APNS Connection#0x503cfa0] Connection established.
I, [2016-04-15T11:11:43.654932 #22319]  INFO -- : [APNS Connection#0x50576c0] Connection established.
I, [2016-04-15T11:11:43.657429 #22319]  INFO -- : [APNS Connection#0x4fc4050] Connection established.
I, [2016-04-15T11:11:43.662997 #22319]  INFO -- : [APNS Connection#0x4fdbe08] Connection established.
I, [2016-04-15T11:11:43.772659 #22319]  INFO -- : [APNS Connection#0x503cfa0] Closing...
I, [2016-04-15T11:11:43.773632 #22319]  INFO -- : [APNS Connection#0x50576c0] Closing...
I, [2016-04-15T11:11:43.776657 #22319]  INFO -- : [APNS Connection#0x4a6faf0] Connecting...
I, [2016-04-15T11:11:43.777045 #22319]  INFO -- : [APNS Connection#0x4a87a88] Connecting...
I, [2016-04-15T11:11:43.779191 #22319]  INFO -- : [APNS Connection#0x4ae3bf8] Connecting...
W, [2016-04-15T11:11:43.783809 #22319]  WARN -- : [APNS Connection#0x4a6faf0] Defer performing request, because the connection has not been established yet.
W, [2016-04-15T11:11:43.786235 #22319]  WARN -- : [APNS Connection#0x4ae3bf8] Defer performing request, because the connection has not been established yet.
I, [2016-04-15T11:11:44.017136 #22319]  INFO -- : [APNS Connection#0x4a87a88] Connection established.
I, [2016-04-15T11:11:44.022112 #22319]  INFO -- : [APNS Connection#0x4a6faf0] Connection established.
I, [2016-04-15T11:11:44.028102 #22319]  INFO -- : [APNS Connection#0x4ae3bf8] Connection established.
I, [2016-04-15T11:11:44.204203 #22319]  INFO -- : [APNS Connection#0x4a6faf0] Closing...
I, [2016-04-15T11:11:44.217866 #22319]  INFO -- : [APNS Connection#0x4ae3bf8] Closing...
I, [2016-04-15T11:12:14.446051 #22319]  INFO -- : [APNS Connection#0x801b4b0] Connecting...
W, [2016-04-15T11:12:14.448687 #22319]  WARN -- : [APNS Connection#0x801b4b0] Defer performing request, because the connection has not been established yet.
I, [2016-04-15T11:12:14.494813 #22319]  INFO -- : [APNS Connection#0x801b4b0] Connection established.
I, [2016-04-15T11:12:14.560924 #22319]  INFO -- : [APNS Connection#0x801b4b0] Closing...
I, [2016-04-15T11:12:28.863597 #22319]  INFO -- : [APNS Connection#0x88b45b8] Connecting...
W, [2016-04-15T11:12:28.866425 #22319]  WARN -- : [APNS Connection#0x88b45b8] Defer performing request, because the connection has not been established yet.
I, [2016-04-15T11:12:28.921952 #22319]  INFO -- : [APNS Connection#0x88b45b8] Connection established.
I, [2016-04-15T11:12:28.993431 #22319]  INFO -- : [APNS Connection#0x88b45b8] Closing...
I, [2016-04-15T11:13:02.284308 #22319]  INFO -- : [APNS Connection#0x7d30ca0] Connecting...
W, [2016-04-15T11:13:02.287045 #22319]  WARN -- : [APNS Connection#0x7d30ca0] Defer performing request, because the connection has not been established yet.
I, [2016-04-15T11:13:02.333417 #22319]  INFO -- : [APNS Connection#0x7d30ca0] Connection established.
I, [2016-04-15T11:13:02.399938 #22319]  INFO -- : [APNS Connection#0x7d30ca0] Closing...
I, [2016-04-15T11:13:07.515136 #22319]  INFO -- : [APNS Connection#0x7a851e0] Connecting...
W, [2016-04-15T11:13:07.517796 #22319]  WARN -- : [APNS Connection#0x7a851e0] Defer performing request, because the connection has not been established yet.
I, [2016-04-15T11:13:07.563011 #22319]  INFO -- : [APNS Connection#0x7a851e0] Connection established.
I, [2016-04-15T11:13:07.628857 #22319]  INFO -- : [APNS Connection#0x7a851e0] Closing...

```

**Comment by alloy** [comment] 2016-04-15 12:24
Yeah that all looks good. It’s going to be hard for me to offer more assistance in this way. What could really help is if you could make a **reduced** sample repo that reproduces the problem.

**Comment by rayway30419** [comment] 2016-04-18 03:28
Hi, @alloy 
The above class is what I use 'lowdown', very simple.  :(
I use gdb to check the dead threads and found that the problem may be cause by Celluloid.
Do you have any idea of that? 
BTW, my server is running on Ubuntu 14.04 LTS
```
 300  Thread 0x7fdef97b7700 (LWP 7631) "spawner.rb:47" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  299  Thread 0x7fdef90b5700 (LWP 7632) "spawner.rb:47" 0x00007fdf2cb41b13 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
  298  Thread 0x7fdee25f8700 (LWP 7636) "spawner.rb:47" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  297  Thread 0x7fdee26f9700 (LWP 7637) "spawner.rb:47" 0x00007fdf2cb41b13 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
  296  Thread 0x7fdedbe7f700 (LWP 7641) "spawner.rb:47" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  295  Thread 0x7fdedb4ff700 (LWP 7642) "spawner.rb:47" 0x00007fdf2cb41b13 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
  294  Thread 0x7fdefa438700 (LWP 7650) "spawner.rb:47" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  293  Thread 0x7fdef9d37700 (LWP 7651) "spawner.rb:47" 0x00007fdf2cb41b13 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
  292  Thread 0x7fdef8f34700 (LWP 7655) "spawner.rb:47" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  291  Thread 0x7fdef85b4700 (LWP 7656) "spawner.rb:47" 0x00007fdf2cb41b13 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
```

**Comment by alloy** [comment] 2016-04-19 09:54
Alas, I do not. It seems like there’s no other course forward but to try to isolate the problem to a very simple reduced example.

**Comment by rayway30419** [comment] 2016-04-27 06:43
Hi @alloy ,
It hard for me to provide a simple reduced sample because I don't have any pem of my own. (owned by company)

But I have some new clues.

After I try to remove the development client (and the recursion of deliver), it won't hold the Active record connection. 

I thought it's a good news but threads was holded by cellouid once a job deliver a push notification by lowdown client.

**Comment by alloy** [comment] 2016-09-08 06:54
Closing due to lack of updates. Feel free to re-open if more info is available.

**Closed by alloy** 2016-09-08 06:54 UTC
